{% set name = "zospy" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zospy-{{ version }}.tar.gz
  sha256: 21f77d281b2f13b55af344340cddf8c93101af724924300b3ca04bad28f3552d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<3.12
    - pythonnet >=3.0.1,<3.1.dev0
    - pandas
    - numpy
    - semver >=3.0.0,<3.1.dev0
    - __win

test:
  imports:
    - zospy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://zospy.readthedocs.io/
  summary: A Python package used to communicate with Zemax OpticStudio through the API
  doc_url: https://zospy.readthedocs.io/
  dev_url: https://github.com/MREYE-LUMC/ZOSPy/
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - LucVV
    - crnh
    - jwmbeenakker
