{% set name = "zospy" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zospy-{{ version }}.tar.gz
  sha256: e88cf1cb0501199c27ba26ac8a4c461e23cf46d31c4461551206c3c61db5db39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.27,<2
    - pip
  run:
    - eval_type_backport
    - lark ~=1.2.0
    - pydantic >=2.4.0
    - python >={{ python_min }},<3.14
    - pythonnet >=3.0.1,<4
    - pandas
    - numpy
    - semver >=3.0.0,<4
    - typing_extensions

test:
  imports:
    - zospy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://zospy.readthedocs.io/
  summary: A Python package used to communicate with Zemax OpticStudio through the API
  doc_url: https://zospy.readthedocs.io/
  dev_url: https://github.com/MREYE-LUMC/ZOSPy/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - LucVV
    - crnh
    - jwmbeenakker
